name: secure_shared_preferences
description: Simple to use yet powerful package to encrypt shared preferences in Android and UserDefaults in iOS.
version: 0.0.4
homepage: https://medium.com/@surajprasannakulkarni/flutter-secured-shared-preferences-feb0e30272bf
repository: https://github.com/the-kool-sk/secure_shared_preferences

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_secure_storage:
    git:
      url: https://github.com/mofsl-flutter/flutter_secure_storage.git
      path: flutter_secure_storage
      ref: master

  cryptography_flutter:
    git:
      url: https://github.com/mofsl-flutter/cryptography.git
      path: cryptography_flutter
      ref: master

  shared_preferences: ^2.0.13
  package_info: ^2.0.2
  cryptography: ^2.0.5
  # encrypt: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  integration_test:
    sdk: flutter

flutter:
  # Add assets or fonts below if needed
  # assets:
  #   - images/example.png

  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
